export * from "./GamingBanner";
export * from "./GamingFeatures";
export * from "./CarouselGames";
export * from "./GameCard";
export * from "./GamingNews";
export * from "./NewCard";
export * from "./DiscoverGames"
export * from "./BgVideo"
export * from "./FAQ"